### ISSUE TITLE
What is the prediction count for the canned demo?

### ISSUE THREAD

**Issue by aurotripathy** [cvlab-stonybrook/LearningToCountEverything#1]
![orange_out](https://user-images.githubusercontent.com/1825684/119724283-630f1e00-be23-11eb-8be5-714ef6a0809b.png)
![IMG_1092_out](https://user-images.githubusercontent.com/1825684/119724358-791cde80-be23-11eb-91e0-2e78bafc67a0.png)

Thank you for your innovative solution to an important problem. 
Reproducing the "eval" portion, I get a prediction count of **29.15**. 

Is that what I should expect? 

Invocation and output below.

`(pyt1.2) auro@auro-ml:~/LearningToCountEverything$ python demo.py --input-image orange.jpg --bbox-file orange_box_ex.txt` 

Namespace(adapt=False, bbox_file='orange_box_ex.txt', gpu_id=0, gradient_steps=100, input_image='orange.jpg', learning_rate=1e-07, model_path='./data/pretrainedModels/FamNet_Save1.pth', output_dir='.', weight_mincount=1e-09, weight_perturbation=0.0001)

`Bounding boxes: [[71, 49, 104, 83], [134, 119, 169, 151], [7, 200, 44, 236]]`

/home/auro/anaconda3/envs/pyt1.2/lib/python3.8/site-packages/torch/nn/functional.py:3060: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn("Default upsampling behavior when mode={} is changed "

`===> The predicted count is:  29.15`
`===> Visualized output is saved to ./orange_out.png`

**Comment by Viresh-R** [comment]
Hey, 
yes, 29.15 is the expected count (without adaptation). With adaptation, you should get a count of 30.05.
