### ISSUE TITLE
Training on new dataset

### ISSUE THREAD

**Issue by Muhibullah1** [cvlab-stonybrook/LearningToCountEverything#10]
Hi,
I tried to train your model on my own dataset. I labeled images on CVAT (you recommended) but the annotations are in XML format and you coded for .json file. I was wondering how did you create json file out of XML, although I manually changed it to json but doest not working. I will be thankful for your guidance

**Comment by Viresh-R** [comment]
Hey,
I used an Xml parser [1] to extract the annotations from CVAT XML files, copied all the annotations into a python dict and saved the dict as a json file.

[1]https://docs.python.org/3/library/xml.etree.elementtree.html

**Comment by Muhibullah1** [comment]
> Hey,
> I used an Xml parser [1] to extract the annotations from CVAT XML files, copied all the annotations into a python dict and saved the dict as a json file.
> 
> [1]https://docs.python.org/3/library/xml.etree.elementtree.html

Thank you for the quick response . I will look at that
