### ISSUE TITLE
About the baselines in your CVPR2021 paper

### ISSUE THREAD

**Issue by zhiyuanyou** [cvlab-stonybrook/LearningToCountEverything#13]
Hello, in your paper, you compare FamNet with object detectors including: Faster RCNN, RetinaNet, and Mask RCNN in Table 2. In my view, Mask RCNN is very similar to Faster RCNN with an additional segmentation head for semantic segmentation. I wonder **the main differences between Faster RCNN and Mask RCNN in your experiments**. 
![企业微信截图_16351600676080](https://user-images.githubusercontent.com/42168004/138685065-5d991248-6f5f-4533-9f7d-cdefb20707fe.png)

**Comment by Viresh-R** [comment]
Hey,
As stated in the paper, we use the pretrained Faster RCNN, RetinaNet and Mask RCNN from the detectron2 library for this experiment. So the main difference between Faster RCNN and Mask RCNN would be the mask prediction branch in Mask RCNN. Note that for our counting experiments, we only use the classification and bounding box regression branches, and ignore the mask prediction branch of Mask RCNN.

**Comment by zhiyuanyou** [comment]
Thanks for your response. I have done  some work following your work and I plan to submit my paper to CVPR2022. However, I am a little confused when I select the Subject Areas. Could you please tell me your selected Subject Areas when you submitted your paper to CVPR2021?
Now I select **Transfer/ low-shot/ long-tail learning** as **Primary**, select **Scene analysis and understanding** and **Vision applications and systems** as Secondary. 

![企业微信截图_16353139653966](https://user-images.githubusercontent.com/42168004/139007883-3ea6b803-e431-4940-ba10-7f52dd12e672.png)

![企业微信截图_1635314210478](https://user-images.githubusercontent.com/42168004/139008039-c837159f-6755-4825-b601-912befc5a0ba.png)

**Comment by Viresh-R** [comment]
From what I remember, we had picked Face and gesture ( since "Face" seemed like a relevant area for crowd counting) and Transfer/Low-shot as the primary and secondary.
