### ISSUE TITLE
Some questions about the FamNet ...

### ISSUE THREAD

**Issue by fhong-jpg** [cvlab-stonybrook/LearningToCountEverything#15]
1. I notice the backbone is fixed in your work, Why not train the backbone during training and adapting? 
2. Why not use lower level features from the backbone? Like "feat_map2" or so.

**Comment by Viresh-R** [comment]
Hey,
1. As stated in the paper, training the backbone may specialize the backbone towards training classes, which may result in poor performance when dealing with unseen classes at test time. Hence, we keep it fixed.
2. we tried, but did not notice any significant boost in performance when using more features. Also, that makes the training slower.

**Comment by fhong-jpg** [comment]
> Hey,
> 
> 1. As stated in the paper, training the backbone may specialize the backbone towards training classes, which may result in poor performance when dealing with unseen classes at test time. Hence, we keep it fixed.
> 2. we tried, but did not notice any significant boost in performance when using more features. Also, that makes the training slower.

Thanks for your answers.
