### ISSUE TITLE
About FSC-147 dataset image licensing?

### ISSUE THREAD

**Issue by ajkailash** [cvlab-stonybrook/LearningToCountEverything#21]
Hi @Viresh-R 

What is the licensing for the 6135 images in the dataset? Can I annotate the images and train the model described in your paper from scratch for commercial purposes?

Thanks for the answer in advance.

Regards,
Lakshmi Narayan

**Comment by Viresh-R** [comment]
Hi,
Our method and code is only shared for non-commercial academic usage. Also, we do not own the copyright to the images. So any user of the dataset is responsible for any infringement issues arising from the dataset usage.
