### ISSUE TITLE
About other benchmarks

### ISSUE THREAD

**Issue by zhiyuanyou** [cvlab-stonybrook/LearningToCountEverything#22]
Hi~

Your work is very interesting, and I am following you work. 
I need to compare the performance of GMN, FamNet, and our model, and your FamNet works well.  
However, GMN always diverges. I have searched github and found 2 repos of GMN. However, both diverges.

I wonder if you could share your GMN code with me. 

My email address is 1368069096@qq.com.

Thanks in advance.

**Comment by Viresh-R** [comment]
Hey,
We used the official Keras implementation of GMN: https://github.com/erikalu/class-agnostic-counting
We did not run into any divergence issues. Note that we used the pretrained GMN provided in the above repo for initialization during our experiments, and we finetuned it on our dataset. If the divergence in training still continues, perhaps the authors of the above GMN repo would be better able to point you in the right direction.
Thanks,
Viresh
