### ISSUE TITLE
Details for training few-shot detectors on FSC 147 dataset.

### ISSUE THREAD

**Issue by flyinglynx** [cvlab-stonybrook/LearningToCountEverything#24]
Thank you for elaborating a comprehensive dataset and a well-designed class-agnostic counting model. We are particular interested in some details on training Few-shot detectors on FSC 147 dataset.

As you have mentioned in the paper, FR few-shot detector and FSOD few-shot detector are trained on FSC 147 dataset for comparison. As the training of detector requires bounding box annotations, did you annotated all bounding boxes on the training set, or **swapping the task head** of detectors to density map regressors?
	
We are currently testing few-shot detectors on FSC 147 dataset. We want to follow your settings. It could not be better if you can release the training code for few-shot detectors. 
	
Thanks again for such a fundamental and solid work.

**Comment by Viresh-R** [comment]
Hey,
Thanks for your interest in our work. For training the few-shot detectors, we propagate the bounding boxes from the exemplars to the dot annotated examples, i.e. we first compute the average bounding box size from the exemplar bounding boxes for an image, and place this average bounding box around the rest of the dot annotated instances (which do not have bounding box annotation) in the image.
Currently we aren't planning on releasing the code for the baseline approaches in our paper, but we would be happy to answer any of your queries about them.

**Comment by flyinglynx** [comment]
Thank you so much for your reply! You have solved my issues.
