### ISSUE TITLE
locate each object which have been counted

### ISSUE THREAD

**Issue by lincong666** [cvlab-stonybrook/LearningToCountEverything#26]
Hi author,thank you for your awesome job.how to locate the object according the density map?

**Comment by Viresh-R** [comment]
Hi,
FamNet wasn't trained for localization task, but for density map prediction task. However, a simple way to obtain the locations of the objects from the predicted density map would be to first find local maximas in the density map, place a bounding box of the same size as the average exemplar size over the local maximas, and do non maximal suppression. For more accurate localization, take a look at some works on localization: https://arxiv.org/abs/1808.01050
