### ISSUE TITLE
LearningToCountEverything

### ISSUE THREAD

**Issue by henbucuoshanghai** [cvlab-stonybrook/LearningToCountEverything#28]
count mang objects/
this paper is last year,how about latest papers this year?

**Comment by Viresh-R** [comment]
https://openaccess.thecvf.com/content/CVPR2022/papers/Shi_Represent_Compare_and_Learn_A_Similarity-Aware_Framework_for_Class-Agnostic_Counting_CVPR_2022_paper.pdf
