### ISSUE TITLE
How to append new data

### ISSUE THREAD

**Issue by timlliu** [cvlab-stonybrook/LearningToCountEverything#31]
I label some new data, but I don't know how to make point map to density map.

**Comment by FCgogogo** [comment]
I have same question

**Comment by Viresh-R** [comment]
Hey,
you can use any adaptive Gaussian density map generation implementation to obtain density maps from the annotated dots, like: https://github.com/leeyeehoo/CSRNet-pytorch/blob/master/make_dataset.ipynb
