### ISSUE TITLE
Bounding boxes for FSC

### ISSUE THREAD

**Issue by jaideep11061982** [cvlab-stonybrook/LearningToCountEverything#34]
Hi @Viresh-R 
how did we get the exemplar bbx for fsc dataset ?

[annotation_FSC147_384.json](https://github.com/cvlab-stonybrook/LearningToCountEverything/blob/master/data/annotation_FSC147_384.json)

did you plot them manually ?

**Comment by Viresh-R** [comment]
Hey, yes, we manually annotated the exemplar bounding boxes.
