### ISSUE TITLE
how to create my datasets 

### ISSUE THREAD

**Issue by Dittonal** [cvlab-stonybrook/LearningToCountEverything#37]
dear author，how to make the datasets, can you tell me ,pls

**Comment by Viresh-R** [comment]
Hey,
you can use CVAT (https://github.com/opencv/cvat) for annotating your images with dots and bounding boxes, and you can use any adaptive Gaussian density map generation scheme to obtain density maps from the annotated dots: https://github.com/leeyeehoo/CSRNet-pytorch/blob/master/make_dataset.ipynb

**Comment by jaideep11061982** [comment]
@Viresh-R  could you let me know these things

1) To generate the points do we need to draw all the bounding boxes firxt ,and get centre points and pass to density fct ?
2) or Points can be simply plotted by marking the center through the tools and pass to density function ?

**Comment by Viresh-R** [comment]
@jaideep11061982 
We followed 2. You could also follow 1 if you have bounding boxes for all the objects. In our case, we annotated only few objects per image with bounding boxes, whereas all the objects were annotated with dots. Hence, we couldn't use 1 in our case.
