### ISSUE TITLE
About annotation.json

### ISSUE THREAD

**Issue by moonbunnyX** [cvlab-stonybrook/LearningToCountEverything#39]
Dear Author, I found that the annotation format in your FSC-147 annotation.json file does not belong to any of the CVAT tools provided. Your json file does not contain the category label, and the categories are in another txt. Can you tell me how you got your annotation.json? I'm trying to construct annotations on other datasets in the same format as FSC147, but I have no idea how to get the annotation.json format. I'd really appreciate it if you could give me some hints.

**Comment by Viresh-R** [comment]
Hey,
We used CVAT to annotate images with dots and bounding boxes. Labels were assigned based on the keyword used in obtaining an image, and CVAT wasn't used for this annotation. We combined all the CVAT annotations and list of keywords and other metadata, and dumped it into a json file.

**Comment by SunCKai** [comment]
Sorry to bother, 
  I also have a similar problem. In the FSC-147 annotation.json file, what does "radio h" and "r" represent respectively and how to get these values. What is the meaning of "box_examples_path", "identity_path", "identity_path_fixed", etc.
  Also, in the "data" folder, "ImageClasses_FSC147. txt" and "Train_Test_Val_FSC_147. json" are generated.
  I will be thankful for your guidance。

**Comment by zhangmiaoyuan** [comment]
> 不好意思打扰了， 我也有类似的问题。FSC-147 annotation.json文件中，“radio h”和“r”分别代表什么以及如何获取这些值。“box_examples_path”、“identity_path”、“identity_path_fixed”等是什么意思。 另外，在“data”文件夹中，生成了“ImageClasses_FSC147.txt”和“Train_Test_Val_FSC_147.json”。 我会感谢你的指导。

i have the sameple trouble about as you said. DO you slove the trouble? Can you tell me

**Comment by Viresh-R** [comment]
Hey,
You can safely ignore "ratio h", "ratio r", "box_examples_path", "identity_path", "identity_path_fixed", and "ImageClasses_FSC147. txt" as these parameters are not required by the training or evaluation code. "Train_Test_Val_FSC_147. json"  is required, and it contains the train, test and val image splits.
