### ISSUE TITLE
COCO-VAL & COCO-TEST

### ISSUE THREAD

**Issue by 1368069096** [cvlab-stonybrook/LearningToCountEverything#7]
Hi~
I am very interested in your work and following your work. I notice that you also implement experiments in a subset of COCO dataset. However, I do not know which images compose the dataset. So it is hard for me to follow your work. Could you please provide the dataset of COCO_VAL & COCO_TEST?

**Comment by Viresh-R** [comment]
Hey,
Thanks for pointing this out ! I have updated Train_Test_Val_FSC_147.json with the Coco splits.
