### ISSUE TITLE
about image 3510.jpg 

### ISSUE THREAD

**Issue by zhiyuanyou** [cvlab-stonybrook/LearningToCountEverything#9]
I found that the image ``3510.jpg'' has 4 queries instead of 3.

**Comment by Viresh-R** [comment]
Hey,
Majority of the images have 3 examples, but there are few images (like 3510.jpg) with more than 3 examples (4 or 5). We have done experiments at our end using strictly 3 examples, and that doesn't result in any significant change in performance.
